//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WarlockSoft.JProyecto {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProyectoPortBinding", Namespace="http://Servicios/")]
    public partial class Proyecto : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback obtenerMisProyectosOperationCompleted;
        
        private System.Threading.SendOrPostCallback agregarTareaAlProyectoOperationCompleted;
        
        private System.Threading.SendOrPostCallback agregarProyectoOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerProyectosOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerTareasOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerDatosProyectoOperationCompleted;
        
        private System.Threading.SendOrPostCallback cambiarEstadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Proyecto() {
            this.Url = global::WarlockSoft.Properties.Settings.Default.WarlockSoft_RefProyecto_Proyecto;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event obtenerMisProyectosCompletedEventHandler obtenerMisProyectosCompleted;
        
        /// <remarks/>
        public event agregarTareaAlProyectoCompletedEventHandler agregarTareaAlProyectoCompleted;
        
        /// <remarks/>
        public event agregarProyectoCompletedEventHandler agregarProyectoCompleted;
        
        /// <remarks/>
        public event obtenerProyectosCompletedEventHandler obtenerProyectosCompleted;
        
        /// <remarks/>
        public event obtenerTareasCompletedEventHandler obtenerTareasCompleted;
        
        /// <remarks/>
        public event obtenerDatosProyectoCompletedEventHandler obtenerDatosProyectoCompleted;
        
        /// <remarks/>
        public event cambiarEstadoCompletedEventHandler cambiarEstadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] obtenerMisProyectos([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_usuario) {
            object[] results = this.Invoke("obtenerMisProyectos", new object[] {
                        id_usuario});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerMisProyectosAsync(int id_usuario) {
            this.obtenerMisProyectosAsync(id_usuario, null);
        }
        
        /// <remarks/>
        public void obtenerMisProyectosAsync(int id_usuario, object userState) {
            if ((this.obtenerMisProyectosOperationCompleted == null)) {
                this.obtenerMisProyectosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerMisProyectosOperationCompleted);
            }
            this.InvokeAsync("obtenerMisProyectos", new object[] {
                        id_usuario}, this.obtenerMisProyectosOperationCompleted, userState);
        }
        
        private void OnobtenerMisProyectosOperationCompleted(object arg) {
            if ((this.obtenerMisProyectosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerMisProyectosCompleted(this, new obtenerMisProyectosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool agregarTareaAlProyecto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nombre, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string descripcion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int diaIni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int mesIni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int anoIni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] double precio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int tiempoEstimado, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int cantidadParticipantes, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string estado, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_usuario, [System.Xml.Serialization.XmlElementAttribute("conocimientos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] conocimientos, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_proyecto) {
            object[] results = this.Invoke("agregarTareaAlProyecto", new object[] {
                        nombre,
                        descripcion,
                        diaIni,
                        mesIni,
                        anoIni,
                        precio,
                        tiempoEstimado,
                        cantidadParticipantes,
                        estado,
                        id_usuario,
                        conocimientos,
                        id_proyecto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void agregarTareaAlProyectoAsync(string nombre, string descripcion, int diaIni, int mesIni, int anoIni, double precio, int tiempoEstimado, int cantidadParticipantes, string estado, int id_usuario, string[] conocimientos, int id_proyecto) {
            this.agregarTareaAlProyectoAsync(nombre, descripcion, diaIni, mesIni, anoIni, precio, tiempoEstimado, cantidadParticipantes, estado, id_usuario, conocimientos, id_proyecto, null);
        }
        
        /// <remarks/>
        public void agregarTareaAlProyectoAsync(string nombre, string descripcion, int diaIni, int mesIni, int anoIni, double precio, int tiempoEstimado, int cantidadParticipantes, string estado, int id_usuario, string[] conocimientos, int id_proyecto, object userState) {
            if ((this.agregarTareaAlProyectoOperationCompleted == null)) {
                this.agregarTareaAlProyectoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnagregarTareaAlProyectoOperationCompleted);
            }
            this.InvokeAsync("agregarTareaAlProyecto", new object[] {
                        nombre,
                        descripcion,
                        diaIni,
                        mesIni,
                        anoIni,
                        precio,
                        tiempoEstimado,
                        cantidadParticipantes,
                        estado,
                        id_usuario,
                        conocimientos,
                        id_proyecto}, this.agregarTareaAlProyectoOperationCompleted, userState);
        }
        
        private void OnagregarTareaAlProyectoOperationCompleted(object arg) {
            if ((this.agregarTareaAlProyectoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.agregarTareaAlProyectoCompleted(this, new agregarTareaAlProyectoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool agregarProyecto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nombre, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int diaIni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int mesIni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int anoIni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int diaFin, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int mesFin, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int anoFin, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string estado, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] double salario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string modoPago, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_usuario) {
            object[] results = this.Invoke("agregarProyecto", new object[] {
                        nombre,
                        diaIni,
                        mesIni,
                        anoIni,
                        diaFin,
                        mesFin,
                        anoFin,
                        estado,
                        salario,
                        modoPago,
                        id_usuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void agregarProyectoAsync(string nombre, int diaIni, int mesIni, int anoIni, int diaFin, int mesFin, int anoFin, string estado, double salario, string modoPago, int id_usuario) {
            this.agregarProyectoAsync(nombre, diaIni, mesIni, anoIni, diaFin, mesFin, anoFin, estado, salario, modoPago, id_usuario, null);
        }
        
        /// <remarks/>
        public void agregarProyectoAsync(string nombre, int diaIni, int mesIni, int anoIni, int diaFin, int mesFin, int anoFin, string estado, double salario, string modoPago, int id_usuario, object userState) {
            if ((this.agregarProyectoOperationCompleted == null)) {
                this.agregarProyectoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnagregarProyectoOperationCompleted);
            }
            this.InvokeAsync("agregarProyecto", new object[] {
                        nombre,
                        diaIni,
                        mesIni,
                        anoIni,
                        diaFin,
                        mesFin,
                        anoFin,
                        estado,
                        salario,
                        modoPago,
                        id_usuario}, this.agregarProyectoOperationCompleted, userState);
        }
        
        private void OnagregarProyectoOperationCompleted(object arg) {
            if ((this.agregarProyectoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.agregarProyectoCompleted(this, new agregarProyectoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] obtenerProyectos() {
            object[] results = this.Invoke("obtenerProyectos", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerProyectosAsync() {
            this.obtenerProyectosAsync(null);
        }
        
        /// <remarks/>
        public void obtenerProyectosAsync(object userState) {
            if ((this.obtenerProyectosOperationCompleted == null)) {
                this.obtenerProyectosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerProyectosOperationCompleted);
            }
            this.InvokeAsync("obtenerProyectos", new object[0], this.obtenerProyectosOperationCompleted, userState);
        }
        
        private void OnobtenerProyectosOperationCompleted(object arg) {
            if ((this.obtenerProyectosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerProyectosCompleted(this, new obtenerProyectosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] obtenerTareas([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_proyecto) {
            object[] results = this.Invoke("obtenerTareas", new object[] {
                        id_proyecto});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerTareasAsync(int id_proyecto) {
            this.obtenerTareasAsync(id_proyecto, null);
        }
        
        /// <remarks/>
        public void obtenerTareasAsync(int id_proyecto, object userState) {
            if ((this.obtenerTareasOperationCompleted == null)) {
                this.obtenerTareasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerTareasOperationCompleted);
            }
            this.InvokeAsync("obtenerTareas", new object[] {
                        id_proyecto}, this.obtenerTareasOperationCompleted, userState);
        }
        
        private void OnobtenerTareasOperationCompleted(object arg) {
            if ((this.obtenerTareasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerTareasCompleted(this, new obtenerTareasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] obtenerDatosProyecto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_proyecto) {
            object[] results = this.Invoke("obtenerDatosProyecto", new object[] {
                        id_proyecto});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerDatosProyectoAsync(int id_proyecto) {
            this.obtenerDatosProyectoAsync(id_proyecto, null);
        }
        
        /// <remarks/>
        public void obtenerDatosProyectoAsync(int id_proyecto, object userState) {
            if ((this.obtenerDatosProyectoOperationCompleted == null)) {
                this.obtenerDatosProyectoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerDatosProyectoOperationCompleted);
            }
            this.InvokeAsync("obtenerDatosProyecto", new object[] {
                        id_proyecto}, this.obtenerDatosProyectoOperationCompleted, userState);
        }
        
        private void OnobtenerDatosProyectoOperationCompleted(object arg) {
            if ((this.obtenerDatosProyectoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerDatosProyectoCompleted(this, new obtenerDatosProyectoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool cambiarEstado([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_proyecto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string estado) {
            object[] results = this.Invoke("cambiarEstado", new object[] {
                        id_proyecto,
                        estado});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cambiarEstadoAsync(int id_proyecto, string estado) {
            this.cambiarEstadoAsync(id_proyecto, estado, null);
        }
        
        /// <remarks/>
        public void cambiarEstadoAsync(int id_proyecto, string estado, object userState) {
            if ((this.cambiarEstadoOperationCompleted == null)) {
                this.cambiarEstadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncambiarEstadoOperationCompleted);
            }
            this.InvokeAsync("cambiarEstado", new object[] {
                        id_proyecto,
                        estado}, this.cambiarEstadoOperationCompleted, userState);
        }
        
        private void OncambiarEstadoOperationCompleted(object arg) {
            if ((this.cambiarEstadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cambiarEstadoCompleted(this, new cambiarEstadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void obtenerMisProyectosCompletedEventHandler(object sender, obtenerMisProyectosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerMisProyectosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerMisProyectosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void agregarTareaAlProyectoCompletedEventHandler(object sender, agregarTareaAlProyectoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class agregarTareaAlProyectoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal agregarTareaAlProyectoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void agregarProyectoCompletedEventHandler(object sender, agregarProyectoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class agregarProyectoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal agregarProyectoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void obtenerProyectosCompletedEventHandler(object sender, obtenerProyectosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerProyectosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerProyectosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void obtenerTareasCompletedEventHandler(object sender, obtenerTareasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerTareasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerTareasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void obtenerDatosProyectoCompletedEventHandler(object sender, obtenerDatosProyectoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerDatosProyectoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerDatosProyectoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void cambiarEstadoCompletedEventHandler(object sender, cambiarEstadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cambiarEstadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cambiarEstadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591